# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[CSTParser]]
deps = ["Tokenize"]
path = "../../packages/CSTParser"
uuid = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
version = "2.5.1-DEV"

[[CodeTracking]]
deps = ["InteractiveUtils", "UUIDs"]
path = "../../packages/CodeTracking"
uuid = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
version = "1.0.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DebugAdapter]]
deps = ["Base64", "JSON", "JSONRPC", "JuliaInterpreter", "Sockets", "UUIDs"]
path = "../../packages/DebugAdapter"
uuid = "17994d07-08fe-42cc-bc1b-7af499b1ea47"
version = "1.0.1-DEV"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocumentFormat]]
deps = ["CSTParser", "FilePathsBase", "Tokenize"]
path = "../../packages/DocumentFormat"
uuid = "ffa9a821-9c82-50df-894e-fbcef3ed31cd"
version = "3.2.1-DEV"

[[FilePathsBase]]
deps = ["Dates", "Mmap", "Printf", "Test", "UUIDs"]
path = "../../packages/FilePathsBase"
uuid = "48062228-2e41-5def-b9a4-89aafe57970f"
version = "0.9.5"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JSON]]
deps = ["Dates", "Mmap", "Unicode"]
path = "../../packages/JSON"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.20.1"

[[JSONRPC]]
deps = ["JSON", "UUIDs"]
path = "../../packages/JSONRPC"
uuid = "b9b8584e-8fd3-41f9-ad0c-7255d428e418"
version = "1.2.1-DEV"

[[JuliaInterpreter]]
deps = ["CodeTracking", "InteractiveUtils", "Random", "UUIDs"]
path = "../../packages/JuliaInterpreter"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.7.26"

[[LanguageServer]]
deps = ["CSTParser", "DocumentFormat", "JSON", "JSONRPC", "Markdown", "REPL", "StaticLint", "SymbolServer", "Tokenize", "URIParser", "UUIDs"]
path = "../../packages/LanguageServer"
uuid = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
version = "3.2.1-DEV"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[PackageCompiler]]
deps = ["Libdl", "Pkg", "UUIDs"]
path = "../../packages/PackageCompiler"
uuid = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
version = "1.2.1"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Test", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[StaticLint]]
deps = ["CSTParser", "Serialization", "SymbolServer"]
path = "../../packages/StaticLint"
uuid = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
version = "4.5.1-DEV"

[[SymbolServer]]
deps = ["InteractiveUtils", "LibGit2", "Markdown", "Pkg", "REPL", "SHA", "Serialization", "Sockets", "UUIDs"]
path = "../../packages/SymbolServer"
uuid = "cf896787-08d5-524d-9de7-132aaa0cb996"
version = "5.1.1-DEV"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[Tokenize]]
path = "../../packages/Tokenize"
uuid = "0796e94c-ce3b-5d07-9a54-7f471281c624"
version = "0.5.8"

[[URIParser]]
deps = ["Unicode"]
path = "../../packages/URIParser"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.1"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VSCodeDebugger]]
deps = ["Base64", "Dates", "InteractiveUtils", "Mmap", "REPL", "Random", "Sockets", "UUIDs", "Unicode"]
path = "../../packages/VSCodeDebugger"
uuid = "a80fdaa1-3292-45d6-85e6-157a63518481"
version = "0.1.0"

[[VSCodeServer]]
deps = ["Base64", "Dates", "InteractiveUtils", "Mmap", "Pkg", "Printf", "Profile", "REPL", "Random", "Sockets", "UUIDs", "Unicode"]
path = "../../packages/VSCodeServer"
uuid = "9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f"
version = "0.0.0"
