[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
CoverageTools = "c36e975a-824b-4404-a568-ef97ca766997"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DebugAdapter = "17994d07-08fe-42cc-bc1b-7af499b1ea47"
ExceptionUnwrapping = "460bff9d-24e4-43bc-9d9f-a8973cb893f4"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
IJuliaCore = "ccee42ee-1239-4771-b50a-e8cbc7e05233"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONRPC = "b9b8584e-8fd3-41f9-ad0c-7255d428e418"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
LoweredCodeUtils = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Salsa = "1fbf2c77-44e2-4d5d-8131-0fa618a5c278"
StaticLint = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"
VSCodeDebugger = "a80fdaa1-3292-45d6-85e6-157a63518481"
VSCodeServer = "9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f"
