language: node_js

node_js:
- "6"

# before_install:
#   - if [ $TRAVIS_OS_NAME == "linux" ]; then
#       export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
#       sh -e /etc/init.d/xvfb start;
#       sleep 3;
#     fi

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.9
#       - libsecret-1-dev

install:
- npm install
- npm install -g vsce
- vsce package

script:
  - npm test --silent

# deploy:
#   provider: releases
#   api_key:
#     secure: 
#   file_glob: true
#   file: "*.vsix"
#   skip_cleanup: true
#   on:
#     repo: JuliaEditorSupport/julia-vscode
#     tags: true
